import type { Metadata } from "next";
import React from "react";
import { Poppins } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

import "~/app/globals.css";

import { AxiomWebVitals } from "next-axiom";

import Providers from "./provider";
import ThemeProvider from "./theme-provider";

const poppins = Poppins({
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  style: ["normal", "italic"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${poppins.variable} font-poppins`}>
          <ThemeProvider>
            <Providers>
              <AxiomWebVitals />
              {/* <SignedOut>
                <SignInButton />
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn> */}
              {children}
            </Providers>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
